[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Impute = "f7bf1975-0170-51b9-8c5f-a992d46b9575"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
StringEncodings = "69024149-9ee7-55f6-a4c4-859efe599b68"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
